Add a notification mechanism for signaling when the mountpoint is ready
Add the notify_pipe option which allows the user to specify the path to
a named pipe. When the mountpoint is ready, a message will be written to
this pipe: 's' for success and 'f' for failure. To avoid blocking the
fuse process until the pipe is read, a new process is spawned which
performs a blocking operation on the pipe. In case of mount failure, no
additional process is created and the main process blocks until the pipe
is read.

An example of operation is provided below:
```
set -x
FIFO=$(mktemp -u)
mkfifo "$FIFO"
./squashfuse_ll -o notify_pipe="$FIFO" -f /path/to/squashfs/archive /tmp/squash&
STATUS=$(head -c1 "$FIFO")
if [ "$STATUS" = "s" ]; then
	echo "Mountpoint contains:"
	ls /tmp/squash
else
	echo "Mounting squashfuse on /tmp/squash failed"
fi
```

Fixes #49

diff --git a/tests/ll-smoke.sh.in b/tests/ll-smoke.sh.in
--- a/tests/ll-smoke.sh.in
+++ b/tests/ll-smoke.sh.in
@@ -60,20 +60,27 @@ for comp in $compressors; do
     mkdir -p "$WORKDIR/mount"
 
     echo "Mounting squashfs image..."
-    $SFLL -f $SFLL_EXTRA_ARGS "$WORKDIR/squashfs.image" "$WORKDIR/mount" >"$WORKDIR/squashfs_ll.log" 2>&1 &
-
-    # Wait up to 5 seconds to be mounted. TSAN builds can take some time to mount.
-    for _ in $(seq 5); do
-    if sq_is_mountpoint "$WORKDIR/mount"; then
-        break
+    FIFO_1=$(mktemp -u)
+    mkfifo "$FIFO_1"
+    $SFLL -f $SFLL_EXTRA_ARGS -o notify_pipe="$FIFO_1" "$WORKDIR/squashfs.image" "$WORKDIR/mount" >"$WORKDIR/squashfs_ll_1.log" 2>&1 &
+    # Wait for the archive to be mounted. TSAN builds can take some time to mount.
+    STATUS=$(head -c1 "$FIFO_1")
+    if [ "$STATUS" != "s" ]; then
+        echo "Image did not mount successfully"
+        cp "$WORKDIR/squashfs_ll_1.log" /tmp/squashfs_ll_1.smoke.log
+        echo "There may be clues in /tmp/squashfs_ll_1.smoke.log"
+        exit 1
     fi
-    sleep 1
-    done
 
-    if ! sq_is_mountpoint "$WORKDIR/mount"; then
-        echo "Image did not mount after 5 seconds."
-        cp "$WORKDIR/squashfs_ll.log" /tmp/squashfs_ll.smoke.log
-        echo "There may be clues in /tmp/squashfs_ll.smoke.log"
+    FIFO_2=$(mktemp -u)
+    mkfifo "$FIFO_2"
+    $SFLL -f $SFLL_EXTRA_ARGS -o notify_pipe="$FIFO_2" "$WORKDIR/squashfs.image" "$WORKDIR/nonexistent_mount" >"$WORKDIR/squashfs_ll_2.log" 2>&1 &
+    # This time the mount command should fail because the mountpoint doesn't exist
+    STATUS=$(head -c1 "$FIFO_2")
+    if [ "$STATUS" != "f" ]; then
+        echo "Image mounted successfully when it should have failed"
+        cp "$WORKDIR/squashfs_ll_2.log" /tmp/squashfs_ll_2.smoke.log
+        echo "There may be clues in /tmp/squashfs_ll_2.smoke.log"
         exit 1
     fi
 
